### ISSUE TITLE
CRP settings are not linked in to elf

### ISSUE THREAD

**Issue by Samonitari** [braun-robotics/rust-lpc82x#37]
When using the device crate or the hal crate, one should specify the memory.x file for the linker script link.x in cortex-m-rt.

I have issues with that, because the CRP feature in these controllers:
- text section should come after 0x300, so _stext needs to be specified in memory.x - update to documentation is needed. It is most likely impossible for user code to be a valid CRP setting, so no harm is done, but for clarity that section should be skipped. If the last bytes are needed in the flash, _stat is unwanted however.
- I had to disable ISP by writing a config word into CRP - 0x2fc - region - it became an ugly hack, modifying the mentioned link.x: adding a crp section before text, and including a linker script in there, that is composed of four BYTE directive - not so happy with it.

I am not very accustomed with linkers, and this should be done maybe in upstream. Just reporting the issue. See LPC82X User Manual - Chapter 25: LPC82x Flash In-System and In-Application Programming for reference
Attaching the files made up the solution. crp.ld is placed in my applications root, beside memory.x
[crp_solution.zip](https://github.com/braun-robotics/rust-lpc82x/files/1686287/crp_solution.zip)

**Comment by hannobraun** [comment]
Thank you for bringing this to my attention. I haven't used CRP before and I'm not exactly a linker expert, so please excuse me if I'm saying anything stupid or wrong.

> text section should come after 0x300, so _stext needs to be specified in memory.x - update to documentation is needed.

Can you point me to the documentation that explains this? Section 25.5.3 of the user manual explains that access to RAM below 0x10000300 is restricted, but I can't find anything about user code needing to be moved.

> It is most likely impossible for user code to be a valid CRP setting, so no harm is done, but for clarity that section should be skipped.

I need to think some more about this, but it seems kinda dodgy to just rely on the fact that random user code is not accidentally activating this option (especially since you could basically brick your chip if that happens, if I understand correctly).

> If the last bytes are needed in the flash, _stat is unwanted however.

I don't understand what you mean by this sentence, and I don't know what _stat is. Can you elaborate?

> I had to disable ISP by writing a config word into CRP - 0x2fc - region - it became an ugly hack, modifying the mentioned link.x: adding a crp section before text, and including a linker script in there, that is composed of four BYTE directive - not so happy with it.

I've had a look at your workaround. You assign to `_stext` in memory.x, line 10. But then there's another assignment to `_stext` in link.x, line 34, before `_stext` is used. Wouldn't that just overwrite your previous assignment?

I any case, it seems like a big waste to give up all those bytes between the vector table and the start of the user code. There must be a better solution.

I'll take a closer look at this later, when I get a chance. Need to do some research :-)

**Comment by Samonitari** [comment]
Hi!

>> text section should come after 0x300, so _stext needs to be specified in memory.x - update to documentation is needed. 

> Can you point me to the documentation that explains this? Section 25.5.3 of the user manual explains that access to RAM below 0x10000300 is restricted, but I can't find anything about user code needing to be moved.

Well, I didn't do deep research, but I think 0x2fc->0x300 is the only region that is used for magic pattern. Currently, after the **vector_table** section at 0x0000 comes the **text** section, and that will occupy the pattern's location - if both section isn't unprobably short.

> I've had a look at your workaround. You assign to _stext in memory.x, line 10. But then there's another assignment to _stext in link.x, line 34, before _stext is used. Wouldn't that just overwrite your previous assignment?

[japaric's memory.x of cortex-m-quickstart](https://github.com/japaric/cortex-m-quickstart/blob/master/memory.x) contained the hint. Looking at the documentation of PROVIDE keyword used in the link.x, it will only define _stext, if it isn't already. The workaround works, btw, I observed the sections before and after with readelf. Also, my board hits init with ISP_ENTRY pin driving a photocoupler - it did not before.
Funny offtopic: it took me two days to finally figure out this. The weak input pullup, that is the default on reset on most pins is diminished to ~1V by the photocouplers, and PIO_12 is not just one of the high-current-drive pins I needed for reliably driving these couplers, but also the ISP_ENTRY pin. It was quite a look on my face, especially as during the board desing I provided jumper pads between PIO_12 and GND in case I would break the PLL and needed ISP_ENTRY to unbrick the core.

>> If the last bytes are needed in the flash, _stat is unwanted however.

> I don't understand what you mean by this sentence, and I don't know what _stat is. Can you elaborate?

Sorry, I meant _stext there too :)
[NXP forum topic by their experts](https://community.nxp.com/thread/388983) describes their solution for inluding the CRP config word - it also provides moving functions between the **vector_table** and the **text** section, if last bytes are needed.

>>It is most likely impossible for user code to be a valid CRP setting, so no harm is done, but for clarity that section should be skipped.

>I need to think some more about this, but it seems kinda dodgy to just rely on the fact that random user code is not accidentally activating this option (especially since you could basically brick your chip if that happens, if I understand correctly).

The magic patterns translates to:
 - mcrmi for NO_ISP -  which seems is not available on these cores. I could not find much on this, not on the list of m0+ set
 - eorsne for CRP1 - same as above
 - strbhi for CRP2 - same as above
 - UNDEFINED instruction for CRP3
So, it IS impossible to accidentally set these on, unless compiler is generating crap.

Should we bother japaric? I sent him an e-mail before figuring out a workaround with some questions, THEN did my homework, I am bit embarassed, but link.x modification is definitely needed, or some ugly pre/postbuild script.

**Comment by hannobraun** [comment]
> Well, I didn't do deep research, but I think 0x2fc->0x300 is the only region that is used for magic pattern. Currently, after the vector_table section at 0x0000 comes the text section, and that will occupy the pattern's location - if both section isn't unprobably short.

Ah, 0x2fc + 4 = 0x300. I somehow managed to miss that. Thank you, it makes a lot more sense now :-)

> Looking at the documentation of PROVIDE keyword used in the link.x, it will only define _stext, if it isn't already.

Okay, makes sense. I thought `PROVIDE` meant something different.

I've done too little work with linker scripts to really know how they work, but just enough that false memories can confuse me :-)

> Sorry, I meant _stext there too :)

Ah, got it, thank you.

> NXP forum topic by their experts describes their solution for inluding the CRP config word - it also provides moving functions between the vector_table and the text section, if last bytes are needed.

That's very useful info. I wonder if you can somehow teach the linker to pack functions into the free space automatically.

> The magic patterns translates to - I built all variation, instead of googleing opcodes:
> [...]

I see, you really did your homework :-)

> Should we bother japaric? I sent him an e-mail before figuring out a workaround with some questions, THEN did my homework, I am bit embarassed, but link.x modification is definitely needed, or some ugly pre/postbuild script.

It happens. I know the feeling of suddenly getting a lot smarter right after sending something dumb to someone :-)

Before bothering japaric, I'd like to think a bit more about this, if you don't mind. I'm not sure yet, but I think your workaround can be streamlined a bit. Maybe we can replace `crp.ld` by setting the value from Rust code [like this](https://github.com/japaric/cortex-m-rt/blob/42388316d9b1647e7f70cb762a84112200b6df9e/src/lib.rs#L321). Although you're probably right that we need to add some mechanism for extending `link.x` to cortex-m-rt. I'll have some time to look into this next week.

**Comment by Samonitari** [comment]
Hi again!

> Before bothering japaric, I'd like to think a bit more about this, if you don't mind. I'm not sure yet, but I think your workaround can be streamlined a bit. Maybe we can replace crp.ld by setting the value from Rust code like this. Although you're probably right that we need to add some mechanism for extending link.x to cortex-m-rt. I'll have some time to look into this next week.

Yes we should definitely discard adding more config files.
Some more information I found: [BYTE, SHORT, LONG and QUAD](http://www.microchip.com/forums/m454846.aspx) - though understanding the linker scripts needs some (I mean thorough) reading, and you definitely would found this.
Lond story short - link.x could have LONG(_symbol_), and define that symbol in Rust code for this. But real generalization I think will prove difficult:
 - if more config word appears - and with the number of cortex-m chips it is quite possible - what?
 - how to make the whole section conditional on existence of some symbol - I think more reading will solve this.

I will drop this issue for the next week, I will report only if significant amount of info appears.
I need to work on the branch I made of this crate (want to rename a lot of crappy enumeratedValue -they really piss me off - and supply it as a patch), and also on the hal (adjust it to the renames, and also write some I2C).
Also I did not reply to your e-mail, but things got hectic again.

**Comment by hannobraun** [comment]
Hi @Samonitari,

> how to make the whole section conditional on existence of some symbol - I think more reading will solve this.

I don't know if this is possible. What I meant is, I think we can probably do away with the file that you specified the value in, in your specific example. I don't think we can go without additional linker script files in the general case.

I haven't had a chance to look into this in detail yet. I hope I can say something more definitive after I do.

> I need to work on the branch I made of this crate (want to rename a lot of crappy enumeratedValue -they really piss me off - and supply it as a patch)

I don't know if I would want to merge patches that just rename things. It depends on whether NXP is going to update the file or not. If they are going to release updates in the future, then any changes we make before then will complicate the update and possibly cause breaking changes for users. On the other hand, if they aren't going to bother, then we are free to fix anything we want, and doing so would definitely be welcome.

I don't know. My current instinct is to wait a bit, since I received a hopeful reply when I sent in my feedback. I also think that users should probably just use the HAL instead of the low-level register mappings, so the crappy names will be hidden behind a nice API anyway. What do you think about that?

> Also I did not reply to your e-mail, but things got hectic again.

Don't worry, take your time.

**Comment by hannobraun** [comment]
It seems that I won't be able to take a closer look this week. I'm sorry, but next should work.

**Comment by hannobraun** [comment]
I've been doing some reading and found a command that looks useful for extending existing linker scripts: `INSERT`, described on [this page](https://sourceware.org/binutils/docs/ld/Miscellaneous-Commands.html#Miscellaneous-Commands)

I still need to do some more reading to figure out if that's a solution for this problem.

**Comment by hannobraun** [comment]
@Samonitari Is this still an issue for you? I haven't done any further research since last posting here (haven't really had the time), but that `INSERT` command I dug up seems promising. At this point it's not clear to me if any action is necessary in this repository.

**Comment by hannobraun** [comment]
Closing because a solution seems to exist and it's unclear whether anything needs to be done in this crate to support it.

@Samonitari Feel free to reopen, if you have anything to add!
